#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0") [--cpu|--gpu]
Build Docker images.
If the type is not specified, it will build both cpu and gpu Docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    if [ $# -eq 0 -o "${1:-}" = "--tf" ]
    then
        if [ -z "$RASTER_VISION_REPO" ]
        then
            BASE_IMAGE="quay.io/azavea/raster-vision:tf-cpu-latest"
        else
            BASE_IMAGE="raster-vision-tf-cpu"
        fi
        docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -t raster-vision-examples-tf-cpu -f Dockerfile .

        if [ -z "$RASTER_VISION_REPO" ]
        then
            BASE_IMAGE="quay.io/azavea/raster-vision:tf-gpu-latest"
        else
            BASE_IMAGE="raster-vision-tf-gpu"
        fi
        docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -t raster-vision-examples-tf-gpu -f Dockerfile .
    fi

    if [ $# -eq 0 -o "${1:-}" = "--pytorch" ]
    then
        if [ -z "$RASTER_VISION_REPO" ]
        then
            BASE_IMAGE="quay.io/azavea/raster-vision:pytorch-latest"
        else
            BASE_IMAGE="raster-vision-pytorch"
        fi

        docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -t raster-vision-examples-pytorch -f Dockerfile .
    fi
fi
