#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0") [--cpu|--gpu]
Build docker images.
If the type is not specified, it will build both cpu and gpu docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    if [ $# -eq 0 -o "${1:-}" = "--cpu" ]
    then
        docker build -t raster-vision-examples-cpu -f Dockerfile-cpu .
    fi
    if [ $# -eq 0 -o "${1:-}" = "--gpu" ]
    then
        docker build -t raster-vision-examples-gpu -f Dockerfile-gpu .
    fi
fi
