#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0") [--cpu|--gpu]
Build docker images.
If the type is not specified, it will build both cpu and gpu docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    if [ $# -eq 0 -o "${1:-}" = "--cpu" ]
    then
        if [ -z "$RASTER_VISION_REPO" ]
        then
            BASE_IMAGE="quay.io/azavea/raster-vision:cpu-0.8"
        else
            BASE_IMAGE="raster-vision-cpu"
        fi

        echo "Using base image '${BASE_IMAGE}'"

        docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -t raster-vision-examples-cpu -f Dockerfile-cpu .
    fi
    if [ $# -eq 0 -o "${1:-}" = "--gpu" ]
    then
        if [ -z "$RASTER_VISION_REPO" ]
        then
            BASE_IMAGE="quay.io/azavea/raster-vision:gpu-0.8"
        else
            BASE_IMAGE="raster-vision-gpu"
        fi

        echo "Using base image '${BASE_IMAGE}'"

        docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -t raster-vision-examples-gpu -f Dockerfile-gpu .
    fi
fi
