#!/bin/bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
REPO_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run console of docker image locally.
All arguments are passed to 'docker run'.
"
}

IMAGE="raster-vision-examples-cpu"
DATA_DIR="${RASTER_VISION_DATA_DIR:-${REPO_ROOT}/data}"

if [ -z "$RASTER_VISION_REPO" ]
then
    SRC_FLAGS=""
else
    SRC_FLAGS="-v ${RASTER_VISION_REPO}/rastervision:/opt/src/rastervision"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    AWS="-e AWS_PROFILE=${AWS_PROFILE:-default} -v ${HOME}/.aws:/root/.aws:ro"
    TENSORBOARD="-p 6006:6006"
    RV_CONFIG="-v ${HOME}/.rastervision:/root/.rastervision:ro"

    docker run ${RUNTIME} ${NAME} --rm -it ${TENSORBOARD} ${AWS} ${RV_CONFIG} \
           -v "$REPO_ROOT"/spacenet:/opt/src/spacenet \
           -v "$REPO_ROOT"/potsdam:/opt/src/potsdam \
	       -v "$REPO_ROOT"/xview:/opt/src/xview \
           -v "$REPO_ROOT"/cowc:/opt/src/cowc \
           -v "$REPO_ROOT"/other:/opt/src/other \
           -v "$REPO_ROOT"/notebooks:/opt/notebooks \
           ${SRC_FLAGS} -v "$DATA_DIR":/opt/data \
           ${IMAGE} "${@:1}"
fi
