#!/bin/bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PROJECT_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"
SRC="${PROJECT_ROOT}"

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run console of docker image locally.
All arguments are passed to 'docker run'.
"
}

IMAGE="raster-vision-examples-cpu"

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    AWS="-e AWS_PROFILE=${AWS_PROFILE:-default} -v ${HOME}/.aws:/root/.aws:ro"
    TENSORBOARD="-p 6008:6006"
    RV_CONFIG="-v ${HOME/.rastervision}:/root/.rastervision:ro"

    docker run ${RUNTIME} ${NAME} --rm -it ${TENSORBOARD} ${AWS} ${RV_CONFIG} \
           -v "$SRC"/spacenet:/opt/src/spacenet \
           -v "$SRC"/notebooks:/opt/notebooks \
           -v "$SRC"/data:/opt/data \
           -p 8080:8080 \
           ${IMAGE} \
           /run_jupyter.sh \
           --ip 0.0.0.0 \
           --port 8080 \
           --no-browser \
           --allow-root \
           --notebook-dir=/opt/notebooks;
fi
